ARG ORG=dockcross
FROM ${ORG}/base:latest

LABEL maintainer="CBC Linux #team-endpoint-linux"

# This is for 64-bit x86_64 Linux machine (Centos 7)

# Crosstool-ng version 2022-05-19
ENV CT_VERSION crosstool-ng-1.25.0

#include "common.crosstool"

# The cross-compiling emulator
RUN apt-get update \
&& apt-get install -y \
  qemu-user \
  qemu-user-static \
&& apt-get clean --yes

# The CROSS_TRIPLE is a configured alias of the "x86_64-centos7-linux-gnu" target.
ENV CROSS_TRIPLE x86_64-centos7-linux-gnu
ENV CROSS_ROOT ${XCC_PREFIX}/${CROSS_TRIPLE}
ENV AS=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-as \
    AR=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ar \
    CC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gcc \
    CPP=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-cpp \
    CXX=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-g++ \
    LD=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ld \
    FC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gfortran \
    GCOV=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gcov \
    GCOVR=/usr/local/bin/gcovr \
    OBJCOPY=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-objcopy \
    READELF=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-readelf \
    STRIP=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-strip

ENV QEMU_LD_PREFIX "${CROSS_ROOT}/${CROSS_TRIPLE}/sysroot"
ENV QEMU_SET_ENV "LD_LIBRARY_PATH=${CROSS_ROOT}/lib:${QEMU_LD_PREFIX}"

COPY Toolchain.cmake ${CROSS_ROOT}/
ENV CMAKE_TOOLCHAIN_FILE ${CROSS_ROOT}/Toolchain.cmake

ENV PKG_CONFIG_PATH /usr/lib/x86_64-centos7-linux-gnu/pkgconfig

# Linux kernel cross compilation variables
ENV PATH ${PATH}:${CROSS_ROOT}/bin
ENV CROSS_COMPILE ${CROSS_TRIPLE}-
ENV ARCH x86_64

# Autodetect the conan profile and create the directory and adjuust some settings from the default
RUN conan profile new default --detect \
 && conan profile update settings.build_type=RelWithDebInfo default \
 && conan profile update settings.compiler.version=11.2 default \
 && conan profile update settings.arch=x86_64 default

#include "common.label-and-env"
